export const LIKERT_OPTIONS = [
  { order: 1, label: "Strongly disagree", value: 1 },
  { order: 2, label: "Disagree", value: 2 },
  { order: 3, label: "Neutral", value: 3 },
  { order: 4, label: "Agree", value: 4 },
  { order: 5, label: "Strongly agree", value: 5 },
] as const;

export const QUESTIONNAIRE_SEED = {
  slug: "daily-health-check",
  title: "Daily Health Check",
  description: "Eight-step questionnaire covering physical, mental, and sleep health.",
  version: 1,
  status: "published",
  questions: [
    {
      step: 1,
      order: 1,
      prompt: "I had enough energy for normal daily activities.",
      dimension: "physical",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 2,
      order: 2,
      prompt: "I moved my body for at least 20 minutes.",
      dimension: "physical",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 3,
      order: 3,
      prompt: "I made balanced food choices today.",
      dimension: "physical",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 4,
      order: 4,
      prompt: "I felt calm and emotionally steady.",
      dimension: "mental",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 5,
      order: 5,
      prompt: "I could focus without feeling overwhelmed.",
      dimension: "mental",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 6,
      order: 6,
      prompt: "I used a healthy strategy to manage stress.",
      dimension: "mental",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 7,
      order: 7,
      prompt: "I slept long enough to feel restored.",
      dimension: "sleep",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
    {
      step: 8,
      order: 8,
      prompt: "My sleep schedule was consistent.",
      dimension: "sleep",
      type: "likert_5",
      required: true,
      maxValue: 5,
      options: LIKERT_OPTIONS,
    },
  ],
} as const;
